### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by rpietro** [t9md/atom-isearch#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [isearch](https://github.com/t9md/atom-isearch) package, v0.1.11
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098:15)
  at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:956:20)
  at Marker.module.exports.Marker.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:141:33)
  at Match.scroll (/Users/rpietro/.atom/packages/isearch/lib/match.coffee:34:27)
  at MatchList.redraw (/Users/rpietro/.atom/packages/isearch/lib/match.coffee:103:13)
  at MatchList.visit (/Users/rpietro/.atom/packages/isearch/lib/match.coffee:77:6)
  at Object.module.exports.start (/Users/rpietro/.atom/packages/isearch/lib/main.coffee:39:16)
  at atom-text-editor.subscriptions.add.atom.commands.add.isearch:search-forward (/Users/rpietro/.atom/packages/isearch/lib/main.coffee:21:38)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:04.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.0 isearch:search-forward (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-light-theme"
    ],
    "disabledPackages": [
      "markdown-preview-plus",
      "language-pfm",
      "atom-terminal"
    ]
  },
  "isearch": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.5.7
isearch, v0.1.11
language-dot, v1.6.0
language-todotxt, v0.6.1
markdown-writer, v1.7.1
pandoc, v0.2.2
repl-term, v0.1.4
sort-lines, v0.11.0
toggle, v0.2.3

# Dev
No dev packages
```

**Comment by t9md** [comment]
I assume you accidentally closed buffer while search panel opened, now when original editor is destroyed, auto-hide search panel.

**Comment by rpietro** [comment]
Thanks. I can create a separate issue for this, but one thing I noticed is
that if you click on a portion of text the search buffer won't close, and
then cmd-i won't take you back to the search button. The issue there is
that I start typing right away and the text will go into my text rather
than the search buffer. Is this something that could be addressed?

Btw, I really like your packages, use a bunch of them all the time

**Comment by t9md** [comment]
From version v0.1.12 , click auto-close search panel.

I know its better to keep open search panel and you can continue to edit & next search.
I can improve like that, but I'm now considering to integrate this isarch package to another simlar my lazy-motion package, so in the meantime I don't want to focus minor issue of this package.

**Comment by rpietro** [comment]
Awesome, thanks.

Any plans regarding regex?

**Comment by t9md** [comment]
I have plan, but currently I'm working on another interesting things (vim-mode improvement etc..), so it will be take time to come back to this and lazy-motion package.
