### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.findFoldMarkers is not a function

### ISSUE THREAD

**Issue by weiying-chen** [t9md/atom-isearch#9]
The error happens whenever I run isearch. This is the Stack Trace (I'm using Atom 1.9.0 and isearch 0.1.13):

```
/C:/Users/User/.atom/packages/isearch/lib/utils.coffee:11
Hide Stack Trace
TypeError: editor.displayBuffer.findFoldMarkers is not a function
    at saveEditorState (file:///C:/Users/User/.atom/packages/isearch/lib/utils.coffee:7:40)
    at Object.module.exports.start (file:///C:/Users/User/.atom/packages/isearch/lib/main.coffee:34:29)
    at atom-text-editor.subscriptions.add.atom.commands.add.isearch:search-forward (file:///C:/Users/User/.atom/packages/isearch/lib/main.coffee:22:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\User\AppData\Local\atom\app-1.9.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\User\AppData\Local\atom\a
```

**Comment by t9md** [comment]
Sorry, I can fix quickly.
But I no longer use this package and don't want to spend any time for this package.
So I unpublished this from atom.io.

Thanks for trying this package and sorry for unpublishing!
